Ecommerce.MVC/Ecommerce.MVC/ViewModels/ArticoliViewModel.cs
using Ecommerce.Core.DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Ecommerce.MVC.ViewModels
{
    public class ArticoliViewModel
    {
        public IEnumerable<ArticoloDTO> Articoli { get; set; }
    }
}

Ecommerce.MVC/Ecommerce.MVC/Controllers/ArticoliController.cs
using Ecommerce.Core;
using Ecommerce.MVC.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Ecommerce.MVC.Controllers
{
    //Permetto l'esecuzione di tutte le action di questo controller solo se ho il ruolo di amministratore
    [Authorize(Roles = "admin")]
    public class ArticoliController : Controller
    {
        public ActionResult Index()
        {
            using (var s = new Services())
            {
                var risultato = s.GetArticoli();
                if (!risultato.Successo)
                {
                    ViewBag.Errore = risultato.Errore;
                    return View();
                }

                return View(new ArticoliViewModel
                {
                    Articoli = risultato.Data
                });
            }
        }

        [HttpGet] // opzionale
        public ActionResult Inserisci()
        {
            return View(new ArticoloViewModel
            {
                IsNuovo = true // Indica alla view che stiamo effettuando un nuovo inserimento
            });
        }

        [HttpPost]
        public ActionResult Inserisci(ArticoloViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            string percorsoImmagine = null;
            if (model.Immagine != null)
            {
                // Se un'immagine è stata postata sul server, la salviamo e otteniamo il percorso in cui è salvata
                var cartellaFisica = Server.MapPath("~/App_Data/ImmaginiArticoli");
                var estensione = Path.GetExtension(model.Immagine.FileName);
                // Per evitare immagini con lo stesso nome, gli riassegnamo un nome univoco con Guid, mantenendo l'estensione di com'è arrivata
                var percorsoFile = Path.Combine(cartellaFisica, $"{Guid.NewGuid()}{estensione}");

                using (var stream = model.Immagine.InputStream)
                using (var fileStream = System.IO.File.Open(percorsoFile, FileMode.CreateNew))
                {
                    stream.CopyTo(fileStream);
                }

                percorsoImmagine = percorsoFile;
            }

            using (var s = new Services())
            {
                var result = s.InserisciArticolo(model.Codice, model.Nome, model.Descrizione,
                     decimal.Parse(model.Prezzo), percorsoImmagine);
                if (!result.Successo)
                {
                    ViewBag.Errore = result.Errore;
                    return View(model);
                }
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet] // opzionale
        public ActionResult Modifica(string codice)
        {
            using (var s = new Services())
            {
                var risultato = s.GetArticolo(codice);
                if (!risultato.Successo)
                    return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);

                var articolo = risultato.Data;

                // Siccome siamo nella action "Modifica" ma vogliamo usare la view "Inserisci", dobbiamo specificarlo
                return View("Inserisci", new ArticoloViewModel
                {
                    IsNuovo = false, // Indica alla view che stiamo effettuando una modifica di un elemento esistente
                    Codice = articolo.Codice,
                    Descrizione = articolo.Descrizione,
                    Nome = articolo.Nome,
                    Prezzo = articolo.Prezzo.ToString()
                });
            }
        }

        [HttpPost]
        public ActionResult Modifica(string codice, ArticoloViewModel model)
        {
            if (!ModelState.IsValid)
                // Siccome siamo nella action "Modifica" ma vogliamo usare la view "Inserisci", dobbiamo specificarlo
                return View("Inserisci", model);

            string percorsoImmagine = null;
            if (model.Immagine != null)
            {
                // Se un'immagine è stata postata sul server, la salviamo e otteniamo il percorso in cui è salvata
                var cartellaFisica = Server.MapPath("~/App_Data/ImmaginiArticoli");
                var estensione = Path.GetExtension(model.Immagine.FileName);
                // Per evitare immagini con lo stesso nome, gli riassegnamo un nome univoco con Guid, mantenendo l'estensione di com'è arrivata
                var percorsoFile = Path.Combine(cartellaFisica, $"{Guid.NewGuid()}{estensione}");

                using (var stream = model.Immagine.InputStream)
                using (var fileStream = System.IO.File.Open(percorsoFile, FileMode.CreateNew))
                {
                    stream.CopyTo(fileStream);
                }

                percorsoImmagine = percorsoFile;
            }

            using (var s = new Services())
            {
                var result = s.ModificaArticolo(codice, model.Nome, model.Descrizione, decimal.Parse(model.Prezzo), percorsoImmagine);
                if (!result.Successo)
                {
                    ViewBag.Errore = result.Errore;
                    // Siccome siamo nella action "Modifica" ma vogliamo usare la view "Inserisci", dobbiamo specificarlo
                    return View("Inserisci", model);
                }
            }

            return RedirectToAction(nameof(Index));
        }

        public ActionResult Immagine(string codice)
        {
            using (var s = new Services())
            {
                var risultato = s.GetArticolo(codice);
                if (!risultato.Successo)
                    return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);

                var articolo = risultato.Data;

                if (string.IsNullOrEmpty(articolo.PercorsoImmagine))
                    return new HttpStatusCodeResult(HttpStatusCode.NotFound);

                // Leggi i bytes dell'immagine salvata sul server
                var bytesImmagine = System.IO.File.ReadAllBytes(articolo.PercorsoImmagine);

                // Restituisci l'immagine al client, con il content/type corrispondente all'estensione dell'immagine
                return File(bytesImmagine, MimeMapping.GetMimeMapping(articolo.PercorsoImmagine));
            }
        }
    }
}

Ecommerce.MVC/Ecommerce.MVC/Views/Articoli/Index.cshtml
@model Ecommerce.MVC.ViewModels.ArticoliViewModel

<table class="table">

    <tr>
        <td>Codice</td>
        <td>Nome</td>
        <td>Operazioni</td>
    </tr>

    @foreach (var articolo in Model.Articoli)
    {
        <tr>
            <td>@articolo.Codice</td>
            <td>@articolo.Nome</td>
            <td><a href="@Url.Action("Modifica", "Articoli", new { @codice = articolo.Codice })" class="btn btn-default">Modifica</a></td>
        </tr>
    }

</table>

Ecommerce.MVC/Ecommerce.MVC/Views/Articoli/Inserisci.cshtml
@model Ecommerce.MVC.ViewModels.ArticoloViewModel

<h3>Nuovo articolo</h3>

@if (!string.IsNullOrEmpty(ViewBag.Errore))
{
    <p class="text-danger">@ViewBag.Errore</p>
}

<!-- Helper per generare <form action="/Articoli/Inserisci" method="post"> -->
@*Se si sta modificando un elemento, passa il parametro @codice al metodo Modifica, per indicare quale articolo modificare*@
@using (var form = Html.BeginForm(Model.IsNuovo ? "Inserisci" : "Modifica", "Articoli", new { @codice = Model.IsNuovo ? null : Model.Codice }, FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @*Aggiungi un input type="hidden" alla form, per ricordare fra gli invii del form se si sta facendo un nuovo inserimento o no*@
    @Html.HiddenFor(m => m.IsNuovo)

    <div>
        @*Se si sta modificando un elemento esistente, aggiungi disabled="disabled" all'input per evitare di far modificare il codice (che è chiave primaria)*@
        Codice: <input type="text" name="@nameof(Model.Codice)" value="@Model.Codice" @Html.Raw(!Model.IsNuovo ? "disabled=\"disabled\"" : "") />
        @Html.ValidationMessageFor(m => m.Codice, null, new { @class = "text-danger" })
    </div>
    <div>
        Nome: <input type="text" name="@nameof(Model.Nome)" value="@Model.Nome" />
        @Html.ValidationMessageFor(m => m.Nome, null, new { @class = "text-danger" })
    </div>
    <div>
        <!-- Sconsigliato: l'associazione fra il campo e la proprietà non è forte -->
        Descrizione: <input type="text" name="@nameof(Model.Descrizione)" value="@Model.Descrizione" />
        @Html.ValidationMessageFor(m => m.Descrizione, null, new { @class = "text-danger" })
    </div>
    <div>
        Prezzo: <input type="text" name="@nameof(Model.Prezzo)" value="@Model.Prezzo" />
        @Html.ValidationMessageFor(m => m.Prezzo, null, new { @class = "text-danger" })
    </div>
    <div>
        PercorsoImmagine: <input type="file" name="@nameof(Model.Immagine)" value="@Model.Immagine" />
        @Html.ValidationMessageFor(m => m.Immagine, null, new { @class = "text-danger" })
    </div>
    <div>
        <p>Immagine esistente:</p>
        <img src="@Url.Action("Immagine", "Articoli", new { @codice = Model.Codice })" style="max-width:100px;" />
    </div>
    <button type="submit">Invia</button>
}
<!-- Alla chiusura stampa </form> -->